### PR TITLE
Update models.py

### PR DESCRIPTION
**Pull request by JinBokLee**
def __str__(self):
        return self.time.strftime("%b. %d, %Y, -%I:%M %p")

%-I -> -%I change plz

### CODE REVIEW

**Comment by jamiecounsell** [comment]
@JinBokLee thanks for the contribution! Can you explain the reason for the change? This seems like something that is quite specific to your use case. You could always subclass this model to make that change if this is the case.

**Comment by jamiecounsell** [comment]
@JinBokLee I'm happy to talk about merging this in if you're able to provide a use case that is outside of your particular application. Otherwise, let me know and I'll close this PR. Thanks!

**Comment by jamiecounsell** [comment]
Closed due to inactivity.

**Comment by srivas001** [comment]
@jamiecounsell The change addresses an error that gets thrown when you create a new comment: "Invalid format string". Also, the hyphen is grammatically unnecessary because you have a comma following the year attribute .

Please remove the "-" from:

def str(self):
return self.time.strftime("%b. %d, %Y, %-I:%M %p")

in admin_comments/models.py line 41



That said, thanks so much for this. You saved me a boat load of time trying to figure out how to add comments to a model object in the admin panel.

**Pull request closed without merging**
